Oilvl_Settings = {}
local cfg = Oilvl_Settings -- so you don't have to edit the rest

-- default value if 1st use
cfg.oilvlframeP = "TOPLEFT";
cfg.oilvlframeX = 22;
cfg.oilvlframeY = -140;
cfg.oilvlscale = 0.8;
cfg.oilvlalpha = 1;
cfg.raidmenuid = 1;
cfg.oilvlms = true; -- mouse scanning for target and raid progression
cfg.oilvlme = true; -- enchant and gem reminder
cfg.oilvlme2 = false; -- best enchant and gem reminder
cfg.oilvlcharilvl = true; -- Char Frame item level
cfg.oilvlrpdetails = true; -- raid progression details
cfg.oilvlgears = {}; -- players equipments
cfg.oilvlcache = {}; -- cache
cfg.oilvlminimapicon = true;
cfg.oilvlprintloaded = false;
cfg.oilvlsummaryshow = true;
cfg.oilvldp = 1; -- decimal places for item level
cfg.oilvlun = true; -- show upgrade number
cfg.oilvlge = true; -- show gem and enchant in character frame and inpection frame
cfg.oilvlcachesw = true; -- enable cache
cfg.oilvlaltclickroll = true; -- alt click roll
cfg.oilvlautoscan = true; -- auto scan ilvl
cfg.oilvlsamefaction = false; -- show ilvl of target for same faction only
cfg.oilvlbagilvl = true; -- show item level of gear in bag
cfg.oilvlcolormatchitemrarity = true; -- item level color follow the color of item rarity
